### ISSUE TITLE
Media Player crashes on Android 9 on audio playback after targetSdkVersion set to 28

### ISSUE THREAD

**Issue by gkv311** [gkv311/sview#75]
Setting android:targetSdkVersion="28", which is required by updated Google Play rules, caused a runtime regression - sView crashes on trying to play audio file.

```
02-01 11:04:27.418 W/ActivityManager( 1846): Permission Denial: startForeground from pid=15003, uid=10130 requires android.permission.FOREGROUND_SERVICE
02-01 11:04:27.419 D/AndroidRuntime(15003): Shutting down VM
--------- beginning of crash
02-01 11:04:27.419 E/AndroidRuntime(15003): FATAL EXCEPTION: main
02-01 11:04:27.419 E/AndroidRuntime(15003): Process: com.sview, PID: 15003
02-01 11:04:27.419 E/AndroidRuntime(15003): java.lang.RuntimeException: Unable to create service com.sview.StMovieService: java.lang.SecurityException: Permission Denial: startForeground from pid=15003, uid=10130 requires android.permission.FOREGROUND_SERVICE
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3545)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.ActivityThread.access$1300(ActivityThread.java:200)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.os.Handler.dispatchMessage(Handler.java:106)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.os.Looper.loop(Looper.java:193)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.ActivityThread.main(ActivityThread.java:6692)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at java.lang.reflect.Method.invoke(Native Method)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-01 11:04:27.419 E/AndroidRuntime(15003): Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=15003, uid=10130 requires android.permission.FOREGROUND_SERVICE
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.os.Parcel.createException(Parcel.java:1950)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.os.Parcel.readException(Parcel.java:1918)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.os.Parcel.readException(Parcel.java:1868)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.Service.startForeground(Service.java:695)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.sview.StMovieService.startForegroundService(StMovieService.java:155)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.sview.StMovieService.onCreate(StMovieService.java:46)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3533)
02-01 11:04:27.419 E/AndroidRuntime(15003):    ... 8 more
02-01 11:04:27.419 E/AndroidRuntime(15003): Caused by: android.os.RemoteException: Remote stack trace:
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9381)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1193)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:874)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20677)
02-01 11:04:27.419 E/AndroidRuntime(15003):    at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:976)
02-01 11:04:27.419 E/AndroidRuntime(15003):
```

![Screenshot_20200201-034837](https://user-images.githubusercontent.com/851453/73589190-0ed08400-44e4-11ea-9460-df2e42ba456e.png)

**Comment by gkv311** [comment]
Fix has been pushed to master.
